require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end
ENV['RCT_NEW_ARCH_ENABLED'] = '0'
min_ios_version_supported = '15.1'
node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

workspace 'BlueWallet'
platform :ios, min_ios_version_supported
prepare_react_native_project!
setup_permissions(['Camera', 'Notifications'])
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

# Define a common function to configure shared settings for targets
def configure_target()
  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"];
  else
    config_command = [
      'node',
      '--no-warnings',
      '--eval',
      'require(require.resolve(\'expo-modules-autolinking\', { paths: [require.resolve(\'expo/package.json\')] }))(process.argv.slice(1))',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
  end

  config = use_native_modules!(config_command)

  use_react_native!(
    # Specify the path directly if use_native_modules! does not provide it
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."

  )
  pod 'react-native-bw-file-access', :path => '../blue_modules/react-native-bw-file-access'
end


target 'BlueWallet' do
  use_expo_modules!
  configure_target()
end

post_install do |installer|
  react_native_post_install(
    installer,
    :mac_catalyst_enabled => true,
    # :ccache_enabled => true
  )
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
      
      if ['React-Core-AccessibilityResources'].include? target.name 
        config.build_settings['CODE_SIGN_STYLE'] = "Manual"
        config.build_settings['CODE_SIGN_IDENTITY'] = "Apple Distribution: Bluewallet Services, S. R. L. (A7W54YZ4WU)"
        config.build_settings['DEVELOPMENT_TEAM'] = "A7W54YZ4WU"
      end
    end
  end
end
